spring:
  mvc:
    static-path-pattern: /**
    view:
      suffix: .jsp
      prefix: /jsps/
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://8.131.85.12:3306/taizhou?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  redis:
    host: 8.131.85.12
    port: 6379
    password:
server:
  jsp-servlet:
    init-parameters:
      development: true
  port: 8089


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
  type-aliases-package: com.taizhou.taizhou_back.pojo
logging:
  level:
    com.taizhou.taizhou_back.mapper: debug
